version: "3.8"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app/logs:/app/logs
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  pgdata: