name: DockerHub Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu klonla
      uses: actions/checkout@v3

    - name: DockerHub'a giriş yap
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Image'ı build et
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bootcamp-final:latest ./app

    - name: DockerHub'a image'ı pushla
      run: docker push ${{ secrets.DOCKER_USERNAME }}/bootcamp-final:latest

