name: Python CI

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Repositoriesi klonla
      uses: actions/checkout@v3
    - name: Python 3.12 kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Kütüphaneleri yükle
      run: |
        python -m pip install --upradge pip
        pip install -r app/requirements.txt
    - name: Pytest ile testleri çalıştır
      run: |
         pip install pytest
         pytest
